repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.2.0
#     hooks:
#     -   id: trailing-whitespace
#     -   id: end-of-file-fixer
#     -   id: check-yaml
#     -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: formatter
        name: formatter
        entry: zsh -c "make fmt"
        language: system
        always_run: true
        pass_filenames: true
    -   id: lintter
        name: lintter
        entry: zsh -c "make lint"
        language: system
        always_run: true
        pass_filenames: true