default:
  db_path: sqlite:///database.db
  proxy_url: socks5://127.0.0.1:1090
production:
  db_path: sqlite:///database.db
  proxy_url: ''
  private_key_path: /etc/letsencrypt/live/aminsalar.me/privkey.pem
  cert_path: /etc/letsencrypt/live/aminsalar.me/fullchain.pem
  domain: aminsalar.me