default:
  db_path: sqlite:///database.db
  proxy_url: socks5://127.0.0.1:1090
production:
  db_path: sqlite:///database.db
  proxy_url: ''
  private_key_path: /etc/teletwitterbot/cert/privkey.pem
  cert_path: /etc/teletwitterbot/cert/cert.pem
  domain: aminsalar.me